# Generated by Django 3.1 on 2020-10-14 10:29

from django.db import migrations, models
import madmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0003_remove_custom_user_model_bankid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(default=madmin.models.auto_generated_bankid, editable=False, max_length=6, unique=True),
        ),
    ]
