# Generated by Django 3.1 on 2020-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0007_remove_custom_user_model_bankid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(default='B-0000', max_length=6, unique=True),
        ),
    ]
