# Generated by Django 3.1 on 2020-10-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0009_auto_20201014_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user_model',
            name='bankid',
        ),
    ]
