# Generated by Django 3.1 on 2020-10-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0011_custom_user_model_bankid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user_model',
            name='bankid',
        ),
    ]
