# Generated by Django 3.1 on 2020-10-14 11:26

from django.db import migrations, models
import madmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0012_remove_custom_user_model_bankid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(blank=True, default=madmin.models.auto_generated_bankid, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
