# Generated by Django 3.1 on 2020-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0014_remove_custom_user_model_bankid'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(blank=True, default='B-0000', editable=False, max_length=6, null=True, unique=True),
        ),
    ]
