# Generated by Django 3.1 on 2020-10-14 11:42

from django.db import migrations, models
import madmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0016_auto_20201014_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(default=madmin.models.auto_generated_bankid, max_length=6, unique=True),
        ),
    ]
