# Generated by Django 3.1 on 2020-10-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0020_auto_20201014_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Configuration',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='Company Id')),
                ('cname', models.CharField(max_length=50, verbose_name='Company Name')),
                ('curls', models.URLField(max_length=100, verbose_name='Company Urls')),
                ('dbrdurls', models.URLField(blank=True, max_length=100, null=True, verbose_name='Deshbord Urls')),
                ('crted_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('uptd_dt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
