# Generated by Django 3.1 on 2020-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0021_company_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='urole',
            field=models.CharField(choices=[('1', 'Super admin'), ('2', 'Teammate'), ('3', 'Operator')], default='3', max_length=30),
        ),
    ]
