# Generated by Django 3.1 on 2020-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0024_default_image_icon_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_image_icon_gallery',
            name='image_path',
            field=models.FileField(unique=True, upload_to='images/'),
        ),
    ]
