# Generated by Django 3.1 on 2020-10-27 10:57

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0026_auto_20201027_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Details',
            fields=[
                ('bot_id', models.AutoField(primary_key=True, serialize=False)),
                ('ct_pos', models.BooleanField(choices=[(True, 'Left'), (False, 'Right')], default=False, verbose_name='Position')),
                ('ct_clr', colorful.fields.RGBColorField(default='#50A59D', verbose_name='Bot Color')),
                ('ct_cstm_icn', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Custom Icon')),
                ('ct_ntn_snd', models.CharField(choices=[('Eventual', 'Eventual'), ('Subtle', 'Subtle'), ('Light', 'Light'), ('Open Ended', 'Open Ended')], default='Eventual', max_length=100, verbose_name='Notification Sound')),
                ('ct_popup', models.BooleanField(default=False, verbose_name='Popup')),
                ('cf_hx_rml', models.BooleanField(choices=[(True, 'Time Basis'), (False, 'Session Basis')], default=False, verbose_name='Chat history removable indicator')),
                ('cf_rml_dys', models.IntegerField(default=1, help_text='30 days', verbose_name='Chat history removal days')),
                ('cf_rml_hrs', models.IntegerField(default=0, help_text='10 hours', verbose_name='Chat history removal hours')),
                ('cf_rml_mnts', models.IntegerField(default=0, help_text='30 minutes', verbose_name='Chat history removal minutes')),
                ('cf_rpls_dly', models.IntegerField(default=5, help_text='0 second', verbose_name='Bot replies delay period')),
                ('cf_dply_inditr', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Chat widget display indicator')),
                ('cf_clct_fdk', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='CollectFeedback')),
                ('sw_wlcmsg', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Show welcome message')),
                ('wm_dflt_lan', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('Portuguese', 'Portuguese')], default='English', max_length=33, verbose_name='default language')),
                ('wm_dflt_wlcmsg', models.TextField(default='Welcome to bot how can i help you!', verbose_name='default welcome message')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmin.company_configuration', verbose_name='company id')),
                ('dflt_icn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='madmin.default_image_icon_gallery')),
            ],
        ),
    ]
