# Generated by Django 3.1 on 2020-10-27 11:49

from django.db import migrations, models
import django.db.models.deletion
import madmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0027_bot_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user_model',
            name='bot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='madmin.bot_details'),
        ),
        migrations.AlterField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(default=madmin.models.auto_generated_bankid, max_length=6),
        ),
    ]
