# Generated by Django 3.1 on 2020-10-28 07:22

from django.db import migrations, models
import django.db.models.deletion
import madmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0028_auto_20201027_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_details',
            name='dflt_icn',
            field=models.ForeignKey(default=madmin.models.default_value_for_icon, on_delete=django.db.models.deletion.CASCADE, to='madmin.default_image_icon_gallery'),
        ),
    ]
