# Generated by Django 3.1 on 2020-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0029_auto_20201028_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(max_length=6),
        ),
    ]
