# Generated by Django 3.1 on 2020-10-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0030_auto_20201028_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='bankid',
            field=models.CharField(blank=True, default='B-0000', max_length=6, null=True),
        ),
    ]
