# Generated by Django 3.1 on 2020-10-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0032_auto_20201028_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_configuration',
            name='cname',
            field=models.CharField(blank=True, default='modefin', max_length=50, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company_configuration',
            name='curls',
            field=models.URLField(blank=True, default='https://modefin.com', max_length=100, null=True, verbose_name='Company Urls'),
        ),
    ]
