# Generated by Django 3.1 on 2020-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0033_auto_20201028_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_configuration',
            name='cname',
            field=models.CharField(default='modefin', max_length=50, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company_configuration',
            name='curls',
            field=models.URLField(default='https://modefin.com', max_length=100, verbose_name='Company Urls'),
        ),
    ]
