# Generated by Django 3.1 on 2020-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0035_auto_20201028_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_details',
            name='ct_cstm_icn',
            field=models.ImageField(blank=True, default='/media/images/Launcher_icon1.png', null=True, upload_to='images/', verbose_name='Custom Icon'),
        ),
    ]
