# Generated by Django 3.1 on 2020-11-10 06:56

from django.db import migrations, models
import django.db.models.deletion
import madmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0039_auto_20201109_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_id', models.CharField(blank=True, default=madmin.models.auto_generated_bankid, max_length=6, null=True)),
                ('bnk_name', models.CharField(default='example', max_length=50, verbose_name='Bank Name')),
                ('bnk_urls', models.URLField(default='example.com', max_length=100, verbose_name='Bank Urls')),
                ('bnk_dbrd_urls', models.URLField(blank=True, max_length=100, null=True, verbose_name='Bank Dashboard Urls')),
                ('max_act_user', models.IntegerField(default=1, verbose_name='Maximum Activate User Allow')),
                ('crted_dt', models.DateTimeField(auto_now_add=True, verbose_name='Bank Created Date')),
                ('uptd_dt', models.DateTimeField(auto_now=True, verbose_name='Bank Updated Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='bot_details',
            name='cid',
        ),
        migrations.DeleteModel(
            name='Company_Configuration',
        ),
        migrations.AddField(
            model_name='bot_details',
            name='bnk_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='madmin.bank_configuration', verbose_name='Bank ID'),
            preserve_default=False,
        ),
    ]
