# Generated by Django 3.1 on 2020-11-10 06:59

from django.db import migrations, models
import madmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0040_auto_20201109_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_configuration',
            name='bnk_id',
            field=models.CharField(default=madmin.models.auto_generated_bankid, max_length=6),
        ),
    ]
